package io.github.m4gshm.spring.data.mock;

import org.springframework.context.annotation.Import;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation replaces repositories with mock ones.
 * Discovers {@link org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport} beans
 * and replaces them by {@link MockRepositoryFactoryBean}.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@Import(RepositoryReplaceRegistrar.class)
public @interface ReplaceRepositoriesByMocks {

    /**
     * Resets the mocked repositories after a Spring test is complete.
     *
     * @return true by default.
     */
    boolean resetAfterTest() default true;

    /**
     * Experimental: Removes a found RepositoryConfigurationExtension beans from the application context.
     *
     * @return true by default.
     */
    boolean removeSourceExtension() default true;

    /**
     * Experimental: Removes a beans generated by the RepositoryConfigurationExtension beans from the application context.
     *
     * @return true by default.
     */
    boolean removeGeneratedByExtension() default true;
}
